### ISSUE TITLE
Bowman Client not supporting Spring boot 3.x

### ISSUE THREAD

**Issue by ShubhamShekhar1996** [hdpe/bowman#47]
Since I upgraded my Springboot version to 3.1.3, I am getting below errors :-

1. class uk.co.blackpepper.bowman.ResourceDeserializer tried to access protected method 'void org.springframework.hateoas.EntityModel.<init>(java.lang.Object, java.lang.Iterable)' (uk.co.blackpepper.bowman.ResourceDeserializer and org.springframework.hateoas.EntityModel are in unnamed module of loader 'app')

2. java.lang.NoSuchMethodError: 'org.springframework.http.HttpStatus org.springframework.web.client.HttpClientErrorException.getStatusCode()'
	at uk.co.blackpepper.bowman.RestOperations.getResource(RestOperations.java:49)
	at uk.co.blackpepper.bowman.Client.get(Client.java:80)
	
	Do we have any support for bowman-client for latest springboot and java versions?
	
	Currently what I am using:-
<dependency>
      <groupId>uk.co.blackpepper.bowman</groupId>
      <artifactId>bowman-client</artifactId>
      <version>0.9.0</version>
    </dependency>

**Comment by hdpe** [comment]
Please try using me.hdpe.bowman:bowman-client:0.11.0 for Spring Boot 3 support.
